### ISSUE TITLE
Command line args: options with args must go LAST.

### ISSUE THREAD

**Issue by Gum-Joe** [Gum-Joe/bedel#8]
As I have just added a new way of adding sub commands, alpha testing has shown that, for some reason, the argument to an options must last on the command line, otherwise you get an error like so:
```
Error: listen EACCES -p
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1378:5)
    at module.exports (C:\Users\Kishan Sambhi\Documents\Projects\bedel\app.js:137:10)
    at Object.module.exports [as handle] (C:\Users\Kishan Sambhi\Documents\Projects\bedel\app\cli\commands\server.js:24:3)
    at Cli.parse (C:\Users\Kishan Sambhi\Documents\Projects\bedel\app\cli\index.js:160:17)
    at Object.<anonymous> (C:\Users\Kishan Sambhi\Documents\Projects\bedel\bin\bedel:26:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)

```

**Comment by Gum-Joe** [comment]
Fixed in `8707b40`
